development:
    domain:             "lvh.me:3000"
    filepicker_api_key: "AR0LrQ7ZBRbaL4HN6BMTDz"
    pusher_key:  "e5aefe0d463e73afe6bc"

production:
    mailgun_gun_api:  "key-65deee3bd721c9bba966ff557d3fc79b"
    mailgun_domian:   "etyme.com"
    domain:           "demoetyme.com"
    filepicker_api_key: "AR0LrQ7ZBRbaL4HN6BMTDz"
    pusher_key:  "e5aefe0d463e73afe6bc"