#development:
#  adapter: async
#
#test:
#  adapter: async
#
#production:
#  adapter: redis
#  url: redis://localhost:6379/1
#  channel_prefix: etyme_production

development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1