default: &default
 adapter: postgresql
 encoding: utf8
 user: root
 password: 12345678
 host: localhost

development:
 <<: *default
 database: etyme_development
test:
 <<: *default
 database: etyme_test

production:
 <<: *default
 host: demoetyme.com
 database: etyme_production_demo