default: &default
 adapter: postgresql
 encoding: utf8
 user: root
 password: 12345678
 port: 5432
 host: localhost
 pool: 5
 timeout: 5000

development:
 <<: *default
 database: etyme_development
test:
 <<: *default
 database: etyme_test

production:
 <<: *default
 database: etyme_production