default: &default
 adapter: postgresql
 encoding: utf8
 user: postgres
 password: postgres
 host: localhost

development:
 <<: *default
 database: etyme_development
test:
 <<: *default
 database: etyme_test

production:
 <<: *default
 database: etyme_production