# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
      redis:
        image: redis
        ports:
          - "6379:6379"
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@master

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundler-cache: true

      - name: Install sodium library
        run: sudo apt-get install libsodium-dev

      - name: Set up database schema
        run: bundle exec bin/rails db:schema:load

      - name: Precompile assets
        run: bundle exec rails assets:precompile

      - name: Run unit tests
        run: bundle exec bin/rails test

      - name: Run system tests
        run: bundle exec bin/rails test:system

      - name: Print server logs
        run: cat log/*.log

#   lint:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
#       - name: Install Ruby and gems
#         uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
#         with:
#           bundler-cache: true
#       # Add or replace any other lints here
#       - name: Security audit dependencies
#         run: bin/bundler-audit --update
#       - name: Security audit application code
#         run: bin/brakeman -q -w2
#       - name: Lint Ruby files
#         run: bin/rubocop --parallel
